replicaCount: 1
storageClass: ""
updateStrategy: "RollingUpdate"
nodeSelector: {}
preventRoot: true

image:
  repository: 348705108113.dkr.ecr.eu-central-1.amazonaws.com/ottimis/php:8.3.11-bullseye
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: "alb"
  certificateArn: ""
  groupName: "frontend-public"
  customAnnotations: {}
  hosts: []
  path: "/"

sftp:
  enabled: false
  users:
    - username: "username"
      # Encrypted password is 'password'
      # openssl passwd -1 -stdin <<< password
      password: "$1$7FmUurbc$9oCGcoGoZSY2P64vtFWtE."
      uid: 1000
      gid: 1000
  image:
    tag: "latest"

deployment:
  customHtaccessCM: ""
  existingSecretsEnv: []
  existingConfigMapsEnv: []
  customIniCM: ""
  resources: {}
  uid: 1000
  gid: 1000
  gracefulShutdownSeconds: 60
  serviceAccountName: ""
  # key-value pairs to set node affinity
  # Example:
    # nodeAffinity:
    #   disktype: ssd
  nodeAffinity: {}
  preventSameNode: true

volumes: []
#  - name: ""
#    mountPaths:
#      - name: moduli
#        path: /var/www/html
#    configMap: ""
#    accessMode: "ReadWriteOnce"
#    size: "8Gi"
#    storageClass: "gp3"
#    # Need sftp.enabled: true to use this
#    sftpAccess: false
