replicaCount: 1
storageClass: ""
updateStrategy: "RollingUpdate"
nodeSelector: {}
preventRoot: true

image:
  repository: 348705108113.dkr.ecr.eu-central-1.amazonaws.com/ottimis/php:8.3.11-bullseye
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "alb"
  certificateArn: ""
  annotations: {}
  hosts: []

persistence:
  accessModes:
    - ReadWriteOnce
  enabled: false
  size: 8Gi

sftp:
  enabled: false
  users:
    - username: "username"
      # Encrypted password is 'password'
      # openssl passwd -1 -stdin <<< password
      password: "$1$7FmUurbc$9oCGcoGoZSY2P64vtFWtE."
      uid: 1000
      gid: 1000
  image:
    tag: "latest"

deployment:
  customHtaccessCM: ""
  existingSecretsEnv: []
  existingConfigMapsEnv: []
  customIniCM: ""
