{{- range $secret := .Values.onePasswordSecrets }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $secret.name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    operator.1password.io/auto-restart: {{ $secret.autoRestart | default true | quote }}
  labels:
    app.kubernetes.io/name: {{ include "wac.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  itemPath: "vaults/{{ $secret.vault | default "eks" }}/items/{{ $secret.item }}"
{{- end }}