{{- range .Values.volumes }}
{{- if not .configMap }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wac.name" $ }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "wac.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  # This annotation is used to keep the PVC when the chart is deleted
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - {{.accessMode }}
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClass }}
{{- end }}
{{- end }}
