{{- if .Values.sftp.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wac.name" . }}-sftp
  namespace: {{ .Release.Namespace | quote }}
data:
  users.conf: |-
    {{- range $user := .Values.sftp.users }}
    {{- range $volume := $.Values.volumes }}
    {{ $user.username }}:{{ $user.password }}:e:{{ $user.uid }}:{{ $user.gid }}:{{ $volume.name }}
    {{- end }}
    {{- end }}
{{- end }}
