apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.name" . }}-admin-password
type: Opaque
data:
  password: {{ - if (lookup "v1" "Secret" .Release.Namespace (include "wordpress.name" . ) "-admin-password").data.password }}
    {{ (lookup "v1" "Secret" .Release.Namespace (include "wordpress.name" . ) "-admin-password").data.password }}
    {{ - else }}
    {{ randAlphaNum 12 | b64enc | quote }}
    {{ - end }}
