apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.name" . }}-admin-password
type: Opaque
data:
  password: {{- $secretName := include "wordpress.name" . | printf "%s-admin-password" -}}
    {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
    {{- if $existingSecret.data.password -}}
    {{ $existingSecret.data.password | quote }}
    {{- else -}}
    {{ randAlphaNum 12 | b64enc | quote }}
    {{- end }}
