name: Release Helm Chart

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      # Step per recuperare il contenuto esistente di gh-pages
      - name: Checkout GitHub Pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./gh-pages

      - name: Package Helm Charts
        run: |
          mkdir -p packages
          for chart in $(ls -d charts/*/); do
            helm package $chart -d packages
          done
          mv packages/* ./gh-pages/

      - name: Add CNAME file
        run: echo "charts.otm.ai" > ./gh-pages/CNAME

      # Step per aggiornare l'indice esistente preservando le versioni precedenti
      - name: Update Helm repo index
        run: |
          helm repo index ./gh-pages --url https://charts.otm.ai --merge ./gh-pages/index.yaml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
